# Use https://travis-ci.org/ for automatic testing
language: go

go:
# Use only the latest version
  - tip

install:
# Resolve dependencies
  - go get -u "github.com/getlantern/systray"
  - go get -u "github.com/cloudfoundry/gosigar"
